export const CRETE_CONTACT_REQUEST = "CRETE_CONTACT_REQUEST";
export const CRETE_CONTACT_SUCCESS = "CRETE_CONTACT_SUCCESS";

export const USER_CONTACTS_REQUEST = "USER_CONTACTS_REQUEST";
export const USER_CONTACTS_SUCCESS = "USER_CONTACTS_SUCCESS";

export const DELETE_CONTACT_REQUEST = "DELETE_CONTACT_REQUEST";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";

export const EMPTY_USERS_SUCCESS = "EMPTY_USERS_SUCCESS";

export const CONTACT_ERROR = "CONTACT_ERROR";