
export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";

export const ALL_PROFILES_REQUEST = "ALL_PROFILES_REQUEST";
export const ALL_PROFILES_SUCCESS = "ALL_PROFILES_SUCCESS";

export const LOG_OUT_PROFILE = "LOG_OUT_PROFILE";


export const PROFILE_ERROR = "PROFILE_ERROR";