export const CRETE_TRANSACTION_REQUEST = "CRETE_TRANSACTION_REQUEST";
export const CRETE_TRANSACTION_SUCCESS = "CRETE_TRANSACTION_SUCCESS";

export const ALL_TRANSACTION_REQUEST = "ALL_TRANSACTION_REQUEST";
export const ALL_TRANSACTION_SUCCESS = "ALL_TRANSACTION_SUCCESS";

export const TRANSACTION_ERROR = "TRANSACTION_ERROR";